// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: mppj.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MPPJHelper_PushRows_FullMethodName = "/mppj_proto.MPPJHelper/PushRows"
	MPPJHelper_PullRows_FullMethodName = "/mppj_proto.MPPJHelper/PullRows"
)

// MPPJHelperClient is the client API for MPPJHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MPPJHelperClient interface {
	PushRows(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EncRow, Void], error)
	PullRows(ctx context.Context, in *Void, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncRowWithHint], error)
}

type mPPJHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewMPPJHelperClient(cc grpc.ClientConnInterface) MPPJHelperClient {
	return &mPPJHelperClient{cc}
}

func (c *mPPJHelperClient) PushRows(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EncRow, Void], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MPPJHelper_ServiceDesc.Streams[0], MPPJHelper_PushRows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EncRow, Void]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPPJHelper_PushRowsClient = grpc.ClientStreamingClient[EncRow, Void]

func (c *mPPJHelperClient) PullRows(ctx context.Context, in *Void, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EncRowWithHint], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MPPJHelper_ServiceDesc.Streams[1], MPPJHelper_PullRows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Void, EncRowWithHint]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPPJHelper_PullRowsClient = grpc.ServerStreamingClient[EncRowWithHint]

// MPPJHelperServer is the server API for MPPJHelper service.
// All implementations must embed UnimplementedMPPJHelperServer
// for forward compatibility.
type MPPJHelperServer interface {
	PushRows(grpc.ClientStreamingServer[EncRow, Void]) error
	PullRows(*Void, grpc.ServerStreamingServer[EncRowWithHint]) error
	mustEmbedUnimplementedMPPJHelperServer()
}

// UnimplementedMPPJHelperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPPJHelperServer struct{}

func (UnimplementedMPPJHelperServer) PushRows(grpc.ClientStreamingServer[EncRow, Void]) error {
	return status.Errorf(codes.Unimplemented, "method PushRows not implemented")
}
func (UnimplementedMPPJHelperServer) PullRows(*Void, grpc.ServerStreamingServer[EncRowWithHint]) error {
	return status.Errorf(codes.Unimplemented, "method PullRows not implemented")
}
func (UnimplementedMPPJHelperServer) mustEmbedUnimplementedMPPJHelperServer() {}
func (UnimplementedMPPJHelperServer) testEmbeddedByValue()                    {}

// UnsafeMPPJHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPPJHelperServer will
// result in compilation errors.
type UnsafeMPPJHelperServer interface {
	mustEmbedUnimplementedMPPJHelperServer()
}

func RegisterMPPJHelperServer(s grpc.ServiceRegistrar, srv MPPJHelperServer) {
	// If the following call pancis, it indicates UnimplementedMPPJHelperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPPJHelper_ServiceDesc, srv)
}

func _MPPJHelper_PushRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MPPJHelperServer).PushRows(&grpc.GenericServerStream[EncRow, Void]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPPJHelper_PushRowsServer = grpc.ClientStreamingServer[EncRow, Void]

func _MPPJHelper_PullRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MPPJHelperServer).PullRows(m, &grpc.GenericServerStream[Void, EncRowWithHint]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPPJHelper_PullRowsServer = grpc.ServerStreamingServer[EncRowWithHint]

// MPPJHelper_ServiceDesc is the grpc.ServiceDesc for MPPJHelper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPPJHelper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mppj_proto.MPPJHelper",
	HandlerType: (*MPPJHelperServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushRows",
			Handler:       _MPPJHelper_PushRows_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PullRows",
			Handler:       _MPPJHelper_PullRows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mppj.proto",
}
