// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v6.32.1
// source: mppj.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_mppj_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_mppj_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_mppj_proto_rawDescGZIP(), []int{0}
}

type EncRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *EncRow) Reset() {
	*x = EncRow{}
	mi := &file_mppj_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncRow) ProtoMessage() {}

func (x *EncRow) ProtoReflect() protoreflect.Message {
	mi := &file_mppj_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncRow.ProtoReflect.Descriptor instead.
func (*EncRow) Descriptor() ([]byte, []int) {
	return file_mppj_proto_rawDescGZIP(), []int{1}
}

func (x *EncRow) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EncRowWithHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *EncRowWithHint) Reset() {
	*x = EncRowWithHint{}
	mi := &file_mppj_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncRowWithHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncRowWithHint) ProtoMessage() {}

func (x *EncRowWithHint) ProtoReflect() protoreflect.Message {
	mi := &file_mppj_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncRowWithHint.ProtoReflect.Descriptor instead.
func (*EncRowWithHint) Descriptor() ([]byte, []int) {
	return file_mppj_proto_rawDescGZIP(), []int{2}
}

func (x *EncRowWithHint) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mppj_proto protoreflect.FileDescriptor

var file_mppj_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x70, 0x70, 0x6a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x70,
	0x70, 0x6a, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64,
	0x22, 0x1c, 0x0a, 0x06, 0x45, 0x6e, 0x63, 0x52, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x24,
	0x0a, 0x0e, 0x45, 0x6e, 0x63, 0x52, 0x6f, 0x77, 0x57, 0x69, 0x74, 0x68, 0x48, 0x69, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x32, 0x7c, 0x0a, 0x0a, 0x4d, 0x50, 0x50, 0x4a, 0x48, 0x65, 0x6c, 0x70,
	0x65, 0x72, 0x12, 0x32, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x52, 0x6f, 0x77, 0x73, 0x12, 0x12,
	0x2e, 0x6d, 0x70, 0x70, 0x6a, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x52,
	0x6f, 0x77, 0x1a, 0x10, 0x2e, 0x6d, 0x70, 0x70, 0x6a, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x28, 0x01, 0x12, 0x3a, 0x0a, 0x08, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x6f,
	0x77, 0x73, 0x12, 0x10, 0x2e, 0x6d, 0x70, 0x70, 0x6a, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x56, 0x6f, 0x69, 0x64, 0x1a, 0x1a, 0x2e, 0x6d, 0x70, 0x70, 0x6a, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x52, 0x6f, 0x77, 0x57, 0x69, 0x74, 0x68, 0x48, 0x69, 0x6e, 0x74,
	0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x6d, 0x70, 0x70, 0x6a, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mppj_proto_rawDescOnce sync.Once
	file_mppj_proto_rawDescData = file_mppj_proto_rawDesc
)

func file_mppj_proto_rawDescGZIP() []byte {
	file_mppj_proto_rawDescOnce.Do(func() {
		file_mppj_proto_rawDescData = protoimpl.X.CompressGZIP(file_mppj_proto_rawDescData)
	})
	return file_mppj_proto_rawDescData
}

var file_mppj_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mppj_proto_goTypes = []any{
	(*Void)(nil),           // 0: mppj_proto.Void
	(*EncRow)(nil),         // 1: mppj_proto.EncRow
	(*EncRowWithHint)(nil), // 2: mppj_proto.EncRowWithHint
}
var file_mppj_proto_depIdxs = []int32{
	1, // 0: mppj_proto.MPPJHelper.PushRows:input_type -> mppj_proto.EncRow
	0, // 1: mppj_proto.MPPJHelper.PullRows:input_type -> mppj_proto.Void
	0, // 2: mppj_proto.MPPJHelper.PushRows:output_type -> mppj_proto.Void
	2, // 3: mppj_proto.MPPJHelper.PullRows:output_type -> mppj_proto.EncRowWithHint
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mppj_proto_init() }
func file_mppj_proto_init() {
	if File_mppj_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mppj_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mppj_proto_goTypes,
		DependencyIndexes: file_mppj_proto_depIdxs,
		MessageInfos:      file_mppj_proto_msgTypes,
	}.Build()
	File_mppj_proto = out.File
	file_mppj_proto_rawDesc = nil
	file_mppj_proto_goTypes = nil
	file_mppj_proto_depIdxs = nil
}
